title: Johnylab
description: >
  Site pessoal de João Batista Ferreira, web designer e developer.
  Moro em Santos e curto padrões web e design moderno.
baseurl: ''
url: 'http://johnylab.net'
markdown: kramdown
paginate: 10
paginate_path: '/blog/:num/'
plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-admin
exclude:
  - gulpfile.js
  - README.md
  - package.json
  - desktop.ini
  - CNAME
collections:
  trabalhos:
    output: false
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      permalink: 'blog/:categories/:title.html'
prose:
  ignore:
  - _data
  - _includes
  - _layouts
  - blog
  - .gitignore
  - CNAME
  - favicon.ico
  - favicon.png
  - feed.xml
  - google6fb37ae82eecf839.html
  - gulpfile.js
  siteurl: http://johnylab.net
  media: img
