title: Johnylab
description: > 
  Site pessoal de João Batista Ferreira, web designer e developer.
  Moro em Santos e curto padrões web e design moderno.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://johnylab.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: 
  - gulpfile.js
  - README.md
  - package.json

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "post"
