title: Johnylab
description: >
  Site pessoal de João Batista Ferreira, web designer e developer.
  Moro em Santos e curto padrões web e design moderno.
baseurl: ''
url: 'http://johnylab.net'
markdown: kramdown
paginate: 10
paginate_path: '/blog/:num/'
plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-admin
exclude:
  - gulpfile.js
  - README.md
  - package.json
  - desktop.ini
  - CNAME
collections:
  trabalhos:
    output: false
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      permalink: 'blog/:categories/:title.html'
prose:
  rooturl: _posts
  siteurl: http://johnylab.net
  media: img
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Título"
      - name: categories
        field:
          element: text
          label: Categoria
      - name: tags
        field:
          element: text
          label: Palavras-chave
      - name: excerpt
        field:
          element: textarea
          label: Description/resumo
      - name: cover
        field:
          element: text
          label: Imagem para redes sociais
